version: '3.8'

services:
  worker:
    container_name: worker
    image: worker_image
    build:
      dockerfile: DockerfileWorker
    environment:
      - MANAGER_URL=http://manager:8080
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8081/health" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - crack-hash-net

  manager:
    container_name: manager
    image: manager_image
    build:
      dockerfile: DockerfileManager
    environment:
      - WORKER_URL=http://worker:8081
    depends_on:
      worker:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - crack-hash-net
networks:
  crack-hash-net: