version: '3.8'

services:
  rabbitmq1:
    image: 'rabbitmq:4.1-rc'
    container_name: rabbitmq1
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
      RABBITMQ_ERLANG_COOKIE: secret
      NODENAME: rabbitmq@rabbitmq1
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q status && rabbitmq-diagnostics -q check_local_alarms" ]
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq1-data:/var/lib/rabbitmq
      - rabbitmq1-logs:/var/log/rabbitmq
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - crack-hash-net
  rabbitmq2:
    image: 'rabbitmq:4.1-rc'
    container_name: rabbitmq2
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
      RABBITMQ_ERLANG_COOKIE: secret
      NODENAME: rabbitmq@rabbitmq2
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q status && rabbitmq-diagnostics -q check_local_alarms" ]
    ports:
      - '5673:5672'
      - '15673:15672'
    volumes:
      - rabbitmq2-data:/var/lib/rabbitmq
      - rabbitmq2-logs:/var/log/rabbitmq
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - crack-hash-net
  rabbitmq3:
    image: 'rabbitmq:4.1-rc'
    container_name: rabbitmq3
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
      RABBITMQ_ERLANG_COOKIE: secret
      NODENAME: rabbitmq@rabbitmq3
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q status && rabbitmq-diagnostics -q check_local_alarms" ]
    ports:
      - '5674:5672'
      - '15674:15672'
    volumes:
      - rabbitmq3-data:/var/lib/rabbitmq
      - rabbitmq3-logs:/var/log/rabbitmq
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - crack-hash-net