version: '3.8'

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo-keyfile:
  mongo1-config:
  mongo2-config:
  mongo3-config:
  mongo1-logs:
  mongo2-logs:
  mongo3-logs:

  rabbitmq1-data:
  rabbitmq2-data:
  rabbitmq3-data:
  rabbitmq1-logs:
  rabbitmq2-logs:
  rabbitmq3-logs:

networks:
  crack-hash-net: