version: '3.8'

services:
  manager:
    container_name: manager
    restart: unless-stopped
    image: manager_image
    build:
      dockerfile: DockerfileManager
    ports:
      - "8081:8080"
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - crack-hash-net
networks:
  crack-hash-net: